title: Best. Home page. Ever.
author: Phil Ma
email: phillio411@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  'The Office' is the best.

# social links
twitter_username: no-twitter-here
github_username:  phillio

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-midnight
